language: csharp
mono: latest
dotnet: 2.1.502
solution: ./SByteDev.Common.Extensions/SByteDev.Common.Extensions.sln
install:
  - nuget restore -source "https://www.nuget.org/api/v2" ./SByteDev.Common.Extensions/SByteDev.Common.Extensions.sln
  - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ./SByteDev.Common.Extensions/SByteDev.Common.Extensions
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./SByteDev.Common.Extensions/SByteDev.Common.Extensions.Tests/bin/Release/netcoreapp2.1/SByteDev.Common.Extensions.Tests.dll